# Generated by Django 5.2.8 on 2025-12-09 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_reservation'),
        ('property', '0003_property_favorited'),
    ]

    operations = [
    ]
