# Generated by Django 5.2.8 on 2025-12-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_merge_0002_reservation_0003_property_favorited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='favorited',
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
    ]
