import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar"
import Modal from "./components/modals/Modal"
import LoginModal from "./components/modals/LoginModal"  //make the hook for the modal then import it in the layout
import SearchModal from "./components/modals/SearchModal"
import SignupModal from "./components/modals/SignupModal"
import AddPropertyModal from "./components/modals/AddPropertyModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DjangoBnb",
  description: "Generated by DjangoBnb",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content = (
    <p>Yo yo</p>
  )
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className="pt-32">
          {children}
        </div>

        <LoginModal />  {/* then pass it here this will not be rendered unless the open is set to true then import it in the UserNav */}
        <SearchModal />
        <SignupModal />
        <AddPropertyModal />
      </body>
    </html>
  );
}
